# 日志等级，设置为默认即可
LogLevel: Info

# 各模块的开关
ModuleSwitch:
  #B站动态订阅
  Bili_Subscription: false
  #公主连结国服动态订阅
  PCR_Subscription: false
  #切噜语翻译
  Cheru: false
  #奇怪的娱乐功能 (随机禁言啥的)
  HaveFun: true
  #随机色图
  Hso: false
  #公会战管理
  PCR_GuildManager: false
  #公会排名查询
  PCR_GuildRank: false
  #慧酱签到
  Suisei: false
  #调试模块
  Debug: false

# 随机色图设置
HsoConfig:
  #色图源 Local/Lolicon/Yukari
  Source: Local
  #Lolicon APIKEY
  LoliconToken: null
  #Yukari APIKEY
  YukariToken: null

# 动态订阅设置
SubscriptionConfig:
  #刷新时间
  FlashTime: 60
  #群组订阅设置
  GroupsConfig:
    - GroupId: [] #群号，可以一次设置多个群
      PCR_Subscription: true #PCR国服动态订阅
      SubscriptionId: [] #B站用户ID